#!/bin/bash

cd "$(dirname "$0")" || return
BASE_URL="$(./base-url)"

CODE="$1"
FIRSTNAME="$2"
LASTNAME="$3"
EMAIL="$4"

if [ $# -ge 4 ] ; then
    curl \
      --include \
      --request POST  \
      --header "Content-Type: application/json" \
      --data '
    {
      "firstName": "'"$FIRSTNAME"'",
      "lastName": "'"$LASTNAME"'",
      "email": "'"$EMAIL"'"
    }' \
      "$BASE_URL"/event/checkin/"$CODE"
else
    echo "Usage: ./checkin code firstname lastname email"
fi
